voat/voat

- Whoaverse/Whoaverse/Scripts/markdownEditor.js
- Whoaverse/Whoaverse/Views/Shared/_MarkdownEditor.cshtml
the order for the submenus was also wrong. I decided to simply give it an ID instead of an hardcoded value
> fixed markdown editor submenus and missing parathesis

- Whoaverse/Whoaverse/Views/Shared/Comments/CommentFlatListButtons/_CommentFlatListButtons.cshtml
- Whoaverse/Whoaverse/Views/Shared/Submissions/SubmissionFlatListButtons/_MSFLButtons.cshtml
This should fix https://github.com/whoaverse/whoaverse/pull/235#issuecomment-69913427
> Fixed javascript for "source" button

- Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
- Whoaverse/Whoaverse/Content/Whoaverse.css
- Whoaverse/Whoaverse/Views/Shared/_AddComment.cshtml
Fixed both issues mentioned [here](https://voat.co/v/test/comments/38011/40388).
> Fixed preview panel being too large and not hide after submitting comment reply

- Whoaverse/Whoaverse/Utils/Components/ContentProcessor.cs
- Whoaverse/Whoaverse/Utils/Components/RegExReplacer.cs
- Whoaverse/Whoaverse/Utils/Formatting.cs
It is sad, but it is fate that all nulls shall be handled.
> The death of null

- Whoaverse/Whoaverse/Views/AjaxViews/_PrivateMessageReplyForm.cshtml
- Whoaverse/Whoaverse/Views/Messaging/Compose.cshtml
As the title says, nothing much to add.
> Added Preview to Compose Private Message and Private Message Reply

- Whoaverse/Whoaverse/Scripts/whoaverse.js
As asked [here](https://voat.co/v/ideasforvoat/comments/41156/40998)
- Focus cursor on textarea for inbox replies to comment replies
- Focus cursor on textarea for inbox replies to post replies
- Focus cursor on textarea for replies to private messages
> Focus cursor on textarea for inbox replies to comments replies, post replies and private messages

- Whoaverse/Whoaverse/Views/About/About.cshtml
Why am I doing this at 5AM? Seriously brain u silly,
> Ridiculously minor change: whoaverse.com -> voat.co in the about page

- Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
- Whoaverse/Whoaverse/Content/Whoaverse.css
This design update is focused on underlined headings throughout Voat. For a while, I just couldn't get them to do their job while also fitting with the rest of the design. I tested out a bunch of colors and styles and I think I found one that works — for now, at least.
Also, I shoveled in some quick tweaks that I noticed while browsing around. I noticed that the expando buttons next to comments started to act up, so they have been straightened out. Last, but not least, I finally remembered to space out the comment voting arrows because I kept accidentally downvoting people while intending to upvote them, instead.
| Before | After |
| --- | --- |
| ![](http://i.imgur.com/32t7buM.png) | ![](http://i.imgur.com/mf6gPfT.png) |
| Before | After |
| --- | --- |
| …
> Heading tweaks, comment expando fix, improved mobile comment arrows

- Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
- Whoaverse/Whoaverse/Content/Whoaverse.css
- Whoaverse/Whoaverse/Views/Shared/_SearchMinimal.cshtml
Atko spent some time on sets, so I will, as well. The existing sets header looked a little old fashioned, so I 'minity'-fied it with a splash of modern:
***
Even with the previous retweaking of the headers in the sidebar, it didn't look quite right. It was kind of confusing and cluttered, so I boxed a few of the spacers up:
> Design set headers to fit with Minity, improve sidebar spacers

- Whoaverse/Whoaverse/Views/Shared/_MarkdownEditor.cshtml
As asked in [this thread](https://voat.co/v/ideasforvoat/comments/42127)
> Auto-focus on "Enter page URL" (markdown editor)

- Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
- Whoaverse/Whoaverse/Content/Whoaverse.css
- Whoaverse/Whoaverse/Views/Shared/Navigation/_TabMenu.cshtml
- Whoaverse/Whoaverse/Views/Shared/Sidebars/_Sidebar.cshtml
- Whoaverse/Whoaverse/Views/Shared/Sidebars/_SidebarComments.cshtml
- Whoaverse/Whoaverse/Views/Shared/Sidebars/_SidebarFrontpage.cshtml
I spent a few hours on this one just trying out different layouts, but this is the one I settled on. They stand out by their color. I wanted to separate the tab menu buttons from the others, but I found that it complicates the layout a lot due to how everything is positioned on the header bar. I hope this is sufficient.
> Implement #201: Separate action buttons from sorting buttons

- Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
- Whoaverse/Whoaverse/Content/Whoaverse.css
This should realign everything swimingly:
> Fix header positioning

- Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
- Whoaverse/Whoaverse/Content/Whoaverse.css
This should fix everything up! Let me know if it doesn't and I'll get right on it!
> Fix pagename positioning

- Whoaverse/Whoaverse/Scripts/markdownEditor.js
- Whoaverse/Whoaverse/Views/Shared/_DefaultMessage.cshtml
- Whoaverse/Whoaverse/Views/Shared/_MarkdownEditor.cshtml
- Whoaverse/Whoaverse/Views/Shared/_VotingIconsSubmission.cshtml
- Updated "like bar" title text from "Red = likes, blue = dislikes" to "Blue = likes, violet = dislikes", in order to reflect the [change to "Cool" color scheme](https://voat.co/v/ideasforvoat/comments/28667).
- [Added Spoiler button to the markdown editor](https://i.imgur.com/oBul3MP.png)
That's all, keep on voatin'!
> Updated "like bar" title text and added Spoiler button to markdown editor

- Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
- Whoaverse/Whoaverse/Content/Whoaverse.css
I tried out a few different solutions until I got one that was pretty simple. After a few hours of on-and-off testing and thinking, I give you: two lines of code changed!
> Fix for #278: login area misplaced on mobile

- Whoaverse/Whoaverse/Views/Home/comments.cshtml
- Whoaverse/Whoaverse/Views/Home/submit.cshtml
- Whoaverse/Whoaverse/Views/Shared/_AddSubmissionSelfpost.cshtml
- Whoaverse/Whoaverse/Views/Subverses/SubverseIndex.cshtml
As requested [here](https://voat.co/v/ideasforvoat/comments/43125)
EDIT: And changed Whoaverse -> Voat as noticed [here](https://voat.co/v/voatdev/comments/43985)
> Added id "custom_css" for subverse custom css

- Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
- Whoaverse/Whoaverse/Content/Whoaverse.css
All issues reported should now be fixed.
> Fix mobile scrollbar, adjust mobile comments, alignment and color adjustments

- Whoaverse/Whoaverse/Views/Account/Manage.cshtml
Should fix the issue [reported here](https://voat.co/v/introductions/comments/51445).
> Fix account management sidebar on mobile view

- Whoaverse/Whoaverse/Scripts/whoaverse.js
- Whoaverse/Whoaverse/Scripts/whoaverse.ui.js
- Whoaverse/Whoaverse/Utils/Components/ContentFilters.cs
- Whoaverse/Whoaverse/Views/Shared/Submissions/_SubmissionLink.cshtml
- Whoaverse/Whoaverse/Views/Shared/Submissions/_SubmissionSelf.cshtml
All expandos are UI processed now. Includes Submission and Comment
expandos.
> UI Expando Extensions (Pre-Release Test)

- Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
- Whoaverse/Whoaverse/Content/Whoaverse.css
- Whoaverse/Whoaverse/Scripts/whoaverse.ui.js
- Whoaverse/Whoaverse/Views/Shared/Submissions/_StickiedSubmission.cshtml
- Whoaverse/Whoaverse/Views/Shared/Submissions/_SubmissionLink.cshtml
- Whoaverse/Whoaverse/Views/Shared/Submissions/_SubmissionSelf.cshtml
Mobile Padding removed, expando buttons show cursor and title
> Small UI Changes

- Whoaverse/Whoaverse/Utils/Formatting.cs
Fix for this:
https://voat.co/v/voatdev/comments/53821
> New Lines break Tables

- Whoaverse/UnitTests/UnitTests.cs
- Whoaverse/Whoaverse/Utils/Submissions.cs
I was in the Unit Tests Project and couldn't help myself
> Recode Submission Age Logic

- Whoaverse/Whoaverse/Views/Help/markdown.cshtml
As asked on [this thread](https://voat.co/v/ideasforvoat/comments/56797)
> Updated Markdown Cheat Sheet to include Spoiler and Headings

- Whoaverse/Whoaverse/Global.asax.cs
Map browser culture to thread culture. Display dates, times, numerics,
and currency according to culture.
> .NET Culture Mapping

- Whoaverse/Whoaverse/Views/Help/markdown.cshtml
This guy discovered this simple and easy fix for the css in the Markdown cheat sheet (issue #334 ). Merge this pull request to find out how! #BuzzfeedCommits
> this fixes #334

- Whoaverse/Whoaverse/Scripts/whoaverse.js
This should fix #284 (which is still closed :P)
>Math! I do it on my head sometimes.
> this fixes #284

- Whoaverse/Whoaverse/Controllers/HomeController.cs
- Whoaverse/Whoaverse/Models/AddSubmissionLinkpost.cs
- Whoaverse/Whoaverse/Models/AddSubmissionSelfpost.cs
This should make the submission title length have to be over 20 characters. Was this what #345 was asking for?
> Submission title length now must be greater than 20

- Whoaverse/Whoaverse/Models/AddSubmissionSelfpost.cs
I made a mistake yesterday and now i feel like a complete idiot. Thanks to quantumwannabe for spotting this.
> Fix the submission error messages that i broke

- Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
- Whoaverse/Whoaverse/Content/Whoaverse.css
- Whoaverse/Whoaverse/Views/Shared/Sidebars/_Sidebar.cshtml
The style for highlighted comments has changed:
The RSS feed icon has been given a class: `rss-icon`.
The minimum CCP section in the sidebar has been adjusted to both look a little neater and be more customizable:
The class `minimum-ccp-downvote` has been added.
> Sidebar bottom layout and highlighted comment adjustments

- Whoaverse/Whoaverse/Views/Shared/Navigation/_TabMenu.cshtml
"Won't somebody please think of the title text!"
> Changed tab menu buttons' titles

- Whoaverse/Whoaverse/Views/Help/Faq.cshtml
- Whoaverse/Whoaverse/Views/Shared/Sidebars/_SidebarUserInfo.cshtml
- Whoaverse/Whoaverse/Views/Shared/_Footer.cshtml
- Whoaverse/Whoaverse/Views/Shared/_SearchInSubverse.cshtml
- Whoaverse/Whoaverse/Views/Shared/_SearchMinimal.cshtml
+ Fixed typo in the FAQ (thanks to [Crackmacs](https://voat.co/user/Crackmacs) for [pointing it out](https://voat.co/v/voatdev/comments/66638))
+ Fixed capitilization in some places
- Removed bit in the FAQ mentioning email for account recovery (not implemented)
+ Added markdown cheat sheet link to the footer (as asked by [Malndor](https://voat.co/user/Malndor) in [this thread](https://voat.co/v/ideasforvoat/comments/56797/85771))
+ Changed the quote in user bio from closing quote (&rdquo;) to opening quote (&ldquo;) (it was closing quote on both beginning and end) (thanks to [AgentOrange](https://voat.co/user/AgentOrange) for [pointing it out](https://voat.co/v/ideasforvoat/comments/60610))
> A few minor updates (title was getting too long)

- Whoaverse/Whoaverse/Views/Shared/Navigation/_DomainsMenu.cshtml
- Whoaverse/Whoaverse/Views/Shared/Navigation/_TabMenu.cshtml
- Whoaverse/Whoaverse/Views/Shared/Sidebars/_Sidebar.cshtml
- Whoaverse/Whoaverse/Views/Shared/Sidebars/_SidebarComments.cshtml
- Whoaverse/Whoaverse/Views/Shared/Sidebars/_SidebarFrontpage.cshtml
Fixes the bug with the Adblock Plus addon for Firefox browsers. [[1]](https://voat.co/v/help/comments/71541/111728) [[2]](https://voat.co/v/introductions/comments/71596/112310/112411#112411)
> Change contribute button class names to pass adblocks

- Whoaverse/Whoaverse/Scripts/whoaverse.js
Fixes #387 and #388.
reply, replyprivatemessage, replyToCommentNotification, and loadMoreSetItems can now only have one request go out at a time.
I touched a few more lines than I should have so the diff looks bigger than it should.
Let me know if there are other requests that should be limited in this way.
> Fixed multiple requests being sent out on actions that append to the DOM

- Whoaverse/Whoaverse/Scripts/whoaverse.js
- Whoaverse/Whoaverse/Views/Home/UserSaved.cshtml
- Whoaverse/Whoaverse/Views/Shared/Submissions/_StickiedSubmission.cshtml
Also fixed a bug where voting on a comment or post would also upvote/downvote the post or comment (respectively) with the same id. I also cached the jQuery objects used for voting because they were being queried 25+ times per vote.
Also fixed a bug where the text wouldn't change when saving a parent comment.
> Save button now shows up for stickies, voting icons are available at /user/saved.

- Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
- Whoaverse/Whoaverse/Content/Whoaverse.css
- Whoaverse/Whoaverse/Views/Shared/Sidebars/_Sidebar.cshtml
- Whoaverse/Whoaverse/Views/Subverses/_SubscribedSubverseDetails.cshtml
Fixes the issues in the following links:
https://voat.co/v/ideasforvoat/comments/93721
https://voat.co/v/ideasforvoat/comments/81864
https://voat.co/v/ideasforvoat/comments/96573
> Mobile layout side margins and subscribe and unsubscribe buttons

- Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
- Whoaverse/Whoaverse/Views/Shared/Sidebars/_Sidebar.cshtml
- Whoaverse/Whoaverse/Views/Shared/Sidebars/_SidebarComments.cshtml
- Whoaverse/Whoaverse/Views/Shared/_SubverseDetails.cshtml
- Whoaverse/Whoaverse/Views/Subverses/_SubscribedSubverseDetails.cshtml
Fixes issues in the following links:
* [Night mode quote css](https://voat.co/v/ideasforvoat/comments/103637)
* [Having unsubscribe and subscribe buttons differ in colour on subverse list page](https://voat.co/v/ideasforvoat/comments/108314)
Number 2 is me adding the subscribe button difference to more pages I overlooked the first time. :-P
> Night mode blockquote contrast, more places for subscribe button differentiation

- Whoaverse/Whoaverse/Controllers/AccountController.cs
- Whoaverse/Whoaverse/Controllers/HomeController.cs
- Whoaverse/Whoaverse/Controllers/MessagingController.cs
- Whoaverse/Whoaverse/Controllers/PartnerController.cs
- Whoaverse/Whoaverse/Controllers/SubversesController.cs
- Whoaverse/Whoaverse/Utils/AntispamUtility.cs
- Whoaverse/Whoaverse/Views/Account/RecoverPassword.cshtml
- Whoaverse/Whoaverse/Views/Account/Register.cshtml
- Whoaverse/Whoaverse/Views/Legal/cla.cshtml
- Whoaverse/Whoaverse/Views/Messaging/Compose.cshtml
- Whoaverse/Whoaverse/Views/Partner/PartnerIntentRegistration.cshtml
- Whoaverse/Whoaverse/Views/Shared/_AddSubmissionLinkpost.cshtml
- Whoaverse/Whoaverse/Views/Shared/_AddSubmissionSelfpost.cshtml
- Whoaverse/Whoaverse/Views/Shared/_Captcha.cshtml
- Whoaverse/Whoaverse/Views/Subverses/_AddNewSubverse.cshtml
- Whoaverse/Whoaverse/Voat.csproj
I've made several improvements to the ReCAPTCHA code, including an attribute to validate the captcha. I've also added checking to places that had the HTML but didn't verify on the server side.
> Recaptcha improvements

- Whoaverse/Whoaverse/Utils/Karma.cs
This reduces the number of queries required for common Karma operations.
> Improving queries for Karma

- Whoaverse/Whoaverse/Views/Help/UserAgreement.cshtml
> Fixed email address on user agreement

- Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
- Whoaverse/Whoaverse/Content/Whoaverse.css
- Whoaverse/Whoaverse/Scripts/whoaverse.js
Add :focus to spoiler revealing styles.
Add document wide click handler for spoiler links to prevent window opening.
> Some fixes for spoiler tags.

- Whoaverse/Whoaverse/Controllers/SubversesController.cs
Blocked and banned verses no longer appear in random and /v/all.
NSFW verses no longer appear in random if adult content is disabled.
> Fixed blocked,banned, and NSFW verses appearing in random.

- Whoaverse/Whoaverse/Views/Shared/Sidebars/_SidebarComments.cshtml
This fixes issue https://github.com/voat/voat/issues/483
This is my first ever proper pull request on Github so my apologies if I buggered something up :)
> Added block button to _SidebarComments

- Whoaverse/Whoaverse/Controllers/WebApiController.cs
- Whoaverse/Whoaverse/Views/Shared/Sidebars/_SidebarUserInfo.cshtml
Fixes alpha user logo not appearing for new users by expanding the date to 08/31 https://github.com/voat/voat/issues/545
Limits API controllers to not pull back from banned subverses
https://github.com/voat/voat/issues/546
> Lockdown API to ignore banned subverses and change alpha user date to 08/31

- Whoaverse/Whoaverse/Controllers/HomeController.cs
- Whoaverse/Whoaverse/Controllers/SearchController.cs
- Whoaverse/Whoaverse/Controllers/SubversesController.cs
- Whoaverse/Whoaverse/Models/whoaverseEntities.cs
> Revert "IAmAGate: Move queries to read-only mirror"

- Voat/Voat.UI/Views/Shared/Sidebars/_Sidebar.cshtml
- Voat/Voat.UI/Views/Shared/Sidebars/_SidebarComments.cshtml
Adds relevant classes to the block and unblock buttons. Addresses immediate issues with #677.
> Add toggle classes to block/unblock buttons.

- Voat/Voat.Business/Utilities/AccountSecurity.cs
- Voat/Voat.Business/Voat.Business.csproj
- Voat/Voat.Tests/Utils/AccountSecurityTests.cs
- Voat/Voat.Tests/Voat.Tests.csproj
> implemented password complexity check utility class + tests

- Voat/Voat.UI/Controllers/SubversesController.cs
- Voat/Voat.UI/Views/Subverses/BannedUsersLog.cshtml
Issue reference - https://github.com/voat/voat/issues/717
Figured this was best in a viewbag as it's simple information.
> Fixed an incorrect count for banned users

- Voat/Voat.Business/Utilities/ThumbGenerator.cs
Simply added a using statement. This may or may not be a contributing factor to #714 (see [github](http://stackoverflow.com/questions/12513078/system-net-webrequest-timeout-error)). In any case this is the correct way to use WebRequests.
> Properly close request in ThumbGernerator

- Voat/Voat.UI/Content/Voat-Dark.css
- Voat/Voat.UI/Content/Voat.css
- Voat/Voat.UI/Views/Help/Faq.cshtml
* Added anchor links to each FAQ point
* Made subverse request point more clearer
* Reflected incorporation in US
* Added IdeasForVoat link
> Updated FAQ

- Voat/Voat.UI/Views/Shared/Sidebars/_SidebarUserInfo.cshtml
Updated "Early Adopter" badge limit date to December 31st
> Fixes #756

- Voat/Voat.UI/Views/Shared/Sidebars/_SidebarSubmissionInfo.cshtml
- Voat/Voat.UI/Views/Shared/Sidebars/_SidebarUserInfo.cshtml
- Voat/Voat.UI/Views/Shared/_DefaultMessage.cshtml
- Voat/Voat.UI/Views/Shared/_LoginPartial.cshtml
- Voat/Voat.UI/Views/Shared/_VotingIconsSubmission.cshtml
Renamed things because consistency is nice
> SCP, CCP, up/downvotes consistency

- docs/Building.md
- docs/Git Branch Model.md
- docs/Style Guide.md
I was looking around at some of the code and felt the project was missing consistency.  I am not an active contributor so I could be completely in the wrong, but I felt that documentation would be nice.  If y'all want, I can flesh these documents out.  Just give me the go ahead and I will get to it.
> Added document stubs

- Voat/Voat.Business/Utilities/CacheHandler.cs
- Voat/Voat.UI/Controllers/ReportController.cs
Quick fix for report comment abuse
> Prevent Spamming of Comment Spam

- Voat/Voat.UI/ddos.htm
The only ones trying to hurt Voat will never read the message anyway, so let’s keep it positive!
> We love our users!

- Voat/Voat.Business/Utilities/UserHelper.cs
- Voat/Voat.UI/Views/Home/_CommentTree.cshtml
- Voat/Voat.UI/Views/Shared/Comments/_CommentBucket.cshtml
Noticed some nested DB calls when debugging another issue.
> Small Performance Improvement

- Voat/Voat.UI/Scripts/voat.ui.js
> Coub embed support

- Voat/Voat.UI/Views/Shared/_Layout.cshtml
Fixing error described in [this post](https://voat.co/v/ideasforvoat/comments/629847)  
Replacement line is based on [this rules file](https://github.com/voat/voat/blob/4baa0cce7ebd9f5e01ed3cd79235f37532d33673/Voat/Voat.Business/Rules/Rules.cs#L135)  
[Previous pull request](https://github.com/voat/voat/pull/793)
> Fixing upvote limit error message - dev branch this time
