voat/voat

Whoaverse/Whoaverse/Content/markdowneditor.css
Whoaverse/Whoaverse/Scripts/markdownEditor.js
Whoaverse/Whoaverse/Views/Help/markdown.cshtml
Whoaverse/Whoaverse/Views/Shared/Comments/CommentFlatListButtons/_CommentFlatListButtons.cshtml
Whoaverse/Whoaverse/Views/Shared/Submissions/SubmissionFlatListButtons/_MSFLButtons.cshtml
Whoaverse/Whoaverse/Views/Shared/Submissions/_MessageSubmissionDetails.cshtml
Whoaverse/Whoaverse/Views/Shared/Submissions/_SubmissionComment.cshtml
Whoaverse/Whoaverse/Views/Shared/_MarkdownEditor.cshtml

Added a submenu to the markdown toolbar where the url for the link can be inserted, instead of using the browser's javascript input prompt.
Added three more examples to the markdown cheat sheet (unordered list, ordered list and horizontal rule)
Added a show source button beneath discussions and comments, so that users can see the markdown that was used instead of the finished html result

Added custom url input field, show source button more examples in the cheat sheet

---

Whoaverse/Whoaverse/Scripts/whoaverse.js
Whoaverse/Whoaverse/Views/Shared/Comments/CommentFlatListButtons/_CommentFlatListButtons.cshtml
Whoaverse/Whoaverse/Views/Shared/Submissions/SubmissionFlatListButtons/_MSFLButtons.cshtml
Whoaverse/Whoaverse/Views/Shared/Submissions/_SubmissionComment.cshtml

"Pull Request 238, Now with 100% less conflicts!"
Took care of the things mentioned [here](https://github.com/whoaverse/whoaverse/pull/236#issuecomment-69928769).
- Source label should no longer be visible for deleted comments/submissions
- Source label is renamed to "hide source" when source is being shown, and renamed back to "source" when it is hidden
Additionally:
- Added comment's last edit time. it should look the same as it does now if the comment wasn't edited, and like this if comment is edited:
>DanielFlamino 1 points (+1|-0) 1 days ago (last edited 3 hours ago)

Updated source label behaviour and added comment's last edit time

---

Whoaverse/Whoaverse/Scripts/whoaverse.js
Whoaverse/Whoaverse/Views/Shared/_MarkdownEditor.cshtml

As the title says:
- Animations for the "source" label and for the markdown toolbar's submenus have been disabled. #BlameAtko :P
- After clicking to insert link, the insert link menu should now be hidden

Disabled animations and Insert link submenu should now hide after inserting link

---

Whoaverse/Whoaverse/Scripts/whoaverse.js
Whoaverse/Whoaverse/Views/AjaxViews/_CommentReplyForm.cshtml
Whoaverse/Whoaverse/Views/Shared/_AddComment.cshtml
Whoaverse/Whoaverse/Views/Shared/_AddSubmissionSelfpost.cshtml
Whoaverse/Whoaverse/Views/Shared/_MarkdownEditor.cshtml

* Moved the submenus below the toolbar as requested [here](https://voat.co/v/voatdev/comments/40844)
* Changed showSubmissionPreview function so that it can be used in other places (instead of only for the Start a Discussion form)
* Updated the Preview button on the Start a Discussion form to reflect the change mentioned above
* Added [Preview button and Preview area to the compose submission comment form](https://i.imgur.com/rqSvf6c.png)
* Added [Preview button and Preview area to the compose comment reply form](https://i.imgur.com/zG6LGJl.png)

Changed Markdown Toolbar's submenus position and added comment preview

---

Whoaverse/Whoaverse/Content/Whoaverse-Dark.css

I have fixed a line I overlooked in the last commit. Now, the havemail icon in night mode should no longer be offset.

Fix night mode havemail icon offset

---

Whoaverse/Whoaverse/Scripts/whoaverse.js
Whoaverse/Whoaverse/Views/Shared/Submissions/_MessageSubmissionDetails.cshtml
Whoaverse/Whoaverse/Views/Shared/Submissions/_SubmissionComment.cshtml
Whoaverse/Whoaverse/Views/Shared/_MarkdownEditor.cshtml

- Changed "source" textarea's class attribute to be the same as the class for the "edit comment" textarea (because this one already has night mode support and, since the source textarea is supposed to give other users the feeling as if they were editing other comments, looks exactly like the edit comment textarea. In case I wasn't clear enough: before ([light](https://i.imgur.com/kUAEhcg.png)/[dark](https://i.imgur.com/pJjRysy.png)) and after ([light](https://i.imgur.com/aR7eByU.png)/[dark](https://i.imgur.com/mgYKna8.png))
- Link expandos should now appear in previews ([Starting a Discussion](https://i.imgur.com/KKE8AVy.png)/[Compose Comment](https://i.imgur.com/zMt9Gyt.png)/[Comment Reply](https://i.imgur.com/scyQPSa.png))
That's all folks!
EDIT: That's not all folks!
- After clicking …

Changed "source" textarea css class and link expandos should appear in previews

---

Whoaverse/Whoaverse/Controllers/CommentController.cs
Whoaverse/Whoaverse/Controllers/HomeController.cs
Whoaverse/Whoaverse/Controllers/MessagingController.cs
Whoaverse/Whoaverse/Utils/Components/ContentFilters.cs
Whoaverse/Whoaverse/Utils/Components/ContentProcessor.cs
Whoaverse/Whoaverse/Utils/Components/NotificationManager.cs
Whoaverse/Whoaverse/Utils/Components/RegExReplacer.cs
Whoaverse/Whoaverse/Utils/Formatting.cs
Whoaverse/Whoaverse/Views/Messaging/Inbox.cshtml
Whoaverse/Whoaverse/Views/Messaging/InboxCommentReplies.cshtml
Whoaverse/Whoaverse/Views/Messaging/InboxPostReplies.cshtml
Whoaverse/Whoaverse/Voat.csproj

This update has the core prototypal structure to parse both incoming and
outgoing user content. Incoming filters process user mention
notifications and outgoing filters convert user mentions, subverse refs,
and raw urls into markdown format.
Both @user and /u/user syntax is supported for user notifications and
links. User notifications happen in all comments and during a post
creation if @user syntax is used in body of the post. Edited
comments/posts are ignored when sending user mention notifications.
User mentioning is limited to the first 5 valid matches, the rest are
ignored. In addition the user mention logic prevents duplicate
notifications if a user is mentioned more than once in a comment/post.
Some small code refactoring in areas I was working also took place.

User Content Processor + Filters

---

Whoaverse/Whoaverse/Scripts/whoaverse.js
Whoaverse/Whoaverse/Views/Shared/Submissions/_SubmissionComment.cshtml
Whoaverse/Whoaverse/Views/Shared/Userprofile/_UserProfileComment.cshtml

- When clicking to reply to a comment, the cursor should now be focused in the comment reply textarea (as asked on [this thread](https://voat.co/v/ideasforvoat/comments/41156))
- Added preview to the "Edit Comment" form
"Thank you for your attention and have a nice day" - Walter Bishop

Focus on textarea when replying to comment and added preview to "edit comment" form

---

Whoaverse/Whoaverse/Scripts/whoaverse.js
Whoaverse/Whoaverse/Views/Shared/Submissions/_SubmissionComment.cshtml

- Fixed edit comment preview not displaying (as mentioned [here](https://github.com/voat/voat/pull/253#issuecomment-71113235))
- When clicking to edit a comment, the cursor should now be focused in the edit comment textarea (similar behaviour as the comment reply)

Fixed edit comment preview not displaying and focus on textarea when editing comment

---

Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
Whoaverse/Whoaverse/Content/Whoaverse.css

* Blue borders for headings were changed to a different shade that did not stand out too much. The previous color was too close to the color reserved for hyperlinks and other clickables.
* The 'load more' button in sets view was given space underneath so it and the next set weren't so close to each other.
* On profiles, in the sidebar, the heading underline was too close to the text, so space was added.

Border adjustments

---

Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
Whoaverse/Whoaverse/Content/Whoaverse.css
Whoaverse/Whoaverse/Views/Shared/_Layout.cshtml
Whoaverse/Whoaverse/Views/Welcome/_FirstTimeVisitorWelcome.cshtml

* The visitor welcome box has been designed to fit with the site while drawing some attention:
* Various `<br />` tags in modal popups have been changed to `<p>` tags so their spacing and style rely on CSS rather than pure HTML. `<br />` tags are best used for single-line breaks used in addresses and unformatted lists.
* The white text on the 'Context' button in the inbox has been corrected.
The idea behind the welcome box design was to both (a) not be distracting and (b) be easy to find. Since many browsers skim the left side of the page, a blue button can catch attention and draw the user to either read the welcome box or just click the button itself. However, when the user is either disinterested or does not need to pay attention to it (registered users who enable private browsing, for …

Modal tweaks

---

Whoaverse/Whoaverse/Scripts/markdownEditor.js
Whoaverse/Whoaverse/Views/Shared/_MarkdownEditor.cshtml

There was no need to use a submenu for the creation of spoiler alerts, because, unlike links, the spoiler alert only has one variable part, the spoiler itself and not a title and url.
In other words:
~~~
[](#s "Keep it simple, stupid")
~~~
~~~
[My Title](My Url)
~~~

Removed unnecessary spoiler creator submenu

---

Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
Whoaverse/Whoaverse/Content/Whoaverse.css
Whoaverse/Whoaverse/Views/Home/UserProfile.cshtml

Sorry for all the recent small pull requests. I consider bugs/oddities high priority, so I like to get them out of the way first.. :-P
Anyway, this was reported [here](https://voat.co/v/voatdev/comments/49127#61149). The quick solution was to apply a distinctive class for the user profile page so I can hide the sidebar completely in mobile view. Later, I'm going to see what I can do to organize the mobile profile page without completely removing the sidebar.

Fix sidebar oddity on UserProfile in mobile view

---

Whoaverse/Whoaverse/Scripts/whoaverse.js
Whoaverse/Whoaverse/Views/Shared/Comments/CommentFlatListButtons/_CommentFlatListButtons.cshtml

Fixes #281 
This should add a parent button to each non root comment.

Added parent button to comments.

---

Whoaverse/Whoaverse/Scripts/whoaverse.ui.js

Saw [this](https://voat.co/v/ideasforvoat/comments/58789) in [/v/ideasforvoat](https://voat.co/v/ideasforvoat). Seemed like something with no downsides to implement.
See below comment for improved version.
This PR should make it so that when a YouTube expando is closed, the video is paused. Since the YouTube player is isolated in an iFrame, I inject the YouTube API in order to control it. This should be only done once.
Because I needed to use the YouTube API, the existing IFrameEmbedderExpando would not work. I copied most of the IFrameEmbedderExpando code and placed it inside of the YouTubeExpando, with the appropriate modifications to attach to the YouTube API. If there is a better way of doing this, let me know as the expando code was very complicated.
Hopefully this works as expected, …

 YouTube videos now pause when expando closed  

---

Whoaverse/Whoaverse/Scripts/whoaverse.js

When scrolling quickly, sometimes comments are loaded more than once. This should fix the problem by blocking further requests until the first one returns.

 Fix duplicate requests when loading more comments.  

---

Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
Whoaverse/Whoaverse/Content/Whoaverse.css
Whoaverse/Whoaverse/Views/Shared/Navigation/_DomainsMenu.cshtml
Whoaverse/Whoaverse/Views/Shared/Navigation/_TabMenu.cshtml
Whoaverse/Whoaverse/Views/Shared/Sidebars/_Sidebar.cshtml
Whoaverse/Whoaverse/Views/Shared/Sidebars/_SidebarComments.cshtml
Whoaverse/Whoaverse/Views/Shared/Sidebars/_SidebarFrontpage.cshtml

As a solution to the issue mentioned [here](https://voat.co/v/CustomizingVoat/comments/60335/101641/102055#102055), the 'Share a link' and 'Start a discussion' contribute buttons/tabs have been given two unique classes: `share-link` and `share-text`.
Additionally, the background contrast between even and odd links has been increased slightly, as promised [many years ago](https://voat.co/v/voatdev/comments/56695/80666/80678#80678).

Unique contribute button classes, increased link background contrast

---

Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
Whoaverse/Whoaverse/Content/Whoaverse.css

As requested [here](https://voat.co/v/ideasforvoat/comments/72951).
Simply changes the original poster's username in their post's comment threads from dark blue to violet to contrast better from other comments.

Change OP username to violet in comment threads

---

Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
Whoaverse/Whoaverse/Content/Whoaverse.css

* I've slightly adjusted the margins and padding of the comment threads to reduce scrolling a bit on **desktop** and
* boosted readability on **mobile**. On *width <= 480px,* margins are reduced slightly and, on *width <= 380px,* font size is reduced one point. [By request](https://voat.co/v/ideasforvoat/comments/74641).

Optimize comment thread spacing

---

Whoaverse/Whoaverse/Views/About/About.cshtml

Changing the wrong e-mail on the about page from team@whoverse.com to team@whoaverse.com

Fixing about page typo, fixes #409

---

Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
Whoaverse/Whoaverse/Content/Whoaverse.css
Whoaverse/Whoaverse/Views/Shared/Submissions/_SubmissionComment.cshtml

The distinction between visited and unvisited links (by color) has been expanded to include areas given the `md` class, which include almost all user text input. This aims to improve UX in situations of posts and comments consisting of many links.<sup>[[1]](https://voat.co/v/ideasforvoat/comments/111814)</sup>
The ability to horizontally resize some text input forms (primarily comment and post submissions) has been disabled to prevent the form from overflowing into inaccessible areas.<sup>[[2]](https://voat.co/v/voatdev/comments/98297)</sup> Most of these text forms are already defined with a 100% width, so the need to horizontally resize them is virtually nonexistent.
Finally, the taglines on comments have received a subtle adjustment (maximize the image in another tab):
Left and right …

Visited/unvisited link distinction, comment taglines, comment box resize

---

Whoaverse/Whoaverse/Views/Shared/_LoginPartial.cshtml

Handicapped and keyboard-centric users shouldn't have to tab past dozens of subverse links to reach the all-important login link.
The "most viewed" links also have tabindex="1" set, but they appear later in the DOM tree so the login and register links will be reached first.
-roboticon

Bring login/register links to front of tab order

---

Whoaverse/Whoaverse/Controllers/RSSController.cs

GUIDs should be unique strings in RSS 2.0
This deals with #441, in terms of some feed readers only showing a single item.

use submission ID as feed item GUID

---

Whoaverse/Whoaverse/Controllers/RSSController.cs
Whoaverse/Whoaverse/Views/Shared/_ListOfSubscribedToSubverses.cshtml

The link is in the default top menu bar, but missing when “Replace top
menu bar with my subscriptions” is enabled in account options

add link to user's sets in top menu bar

---

Whoaverse/Whoaverse/Views/Shared/_Layout.cshtml

The default theme is light, so the default theme if the selection state is missing should be light, not _no_  theme.

Default theme for corrupted theme selection state to light

---

Whoaverse/Whoaverse/Content/Whoaverse-Dark.css
Whoaverse/Whoaverse/Content/Whoaverse.css

Fixes the issue presented [here](https://voat.co/v/test/comments/164315).<sup>[[archive]](http://web.archive.org/web/20150624220356/https://voat.co/v/test/comments/164315)</sup>
Titles on links and self-posts will now break overly-long one-word titles into a new line if necessary. In all other cases, wrapping behavior should remain normal.

Fixes overly-long one-word titles not wrapping

---

Voat/Voat.UI/Utils/User.cs

You're not returning the percentages elsewhere, so you really don't need to convert them when you're really just checking if they downvote more than they upvote.
If you want to use different percentages later, multiply commentUpvotes by `(1 - x) / x` where `x` is the desired ratio of downvotes from 0.00 to 1.00. (e.g. if you consider anyone who votes more than 30% down a meanie, use `commentDownvotes > commentUpvotes * (0.7 / 0.3)` instead.

Get rid of the redundant percentage checking.

---

Voat/Voat.Business/Utilities/UrlUtility.cs
Voat/Voat.Tests/Utils/UrlUtilityTests.cs

When you go to https://voat.co/submit?linkpost=true, enter  https://lwn.net/Articles/653411/ as URL and let voat suggest a title, the title will begin with `&quot;Big data&quot;` instead of `"Bit data"`. This is because the UrlUtility doesn't decode HTML entities if the title is discovered via HTML (it does decode HTML entities if the title is discovered via OpenGraph).
The first commit is a one-line fix for this. I verified locally that this produces the desired result and doesn't open up XSS vulnerabilities.
The second commit adds a unit test for this. If you are internally replacing unit tests just say a word and I will remove the second commit again.

Fix encoding for Suggest Title

---

Voat/Voat.UI/Views/Shared/_Captcha.cshtml

Since Voat’s UI is in English, I think it’s reasonable to set reCAPTCHA to English.
This will help avoid problems like [this](https://voat.co/v/voatdev/comments/310530), where a user is travelling to different countries or using a VPN and receives a captcha in a language they don’t understand.
This should be a temporary measure. If and when Voat is localised then the language value should be taken from some sort of account settings.

Set reCAPTCHA language to English

---

README.md

Made the link relative so that the image is displayed even if voat.co site is down. See issue #783

Fixed link to Voat mascot (fix #783)

---

Voat/Voat.UI/Models/ViewModels/SubverseBanViewModel.cs

Ban reason was limited to 23 characters, should now be 50.

Corrected a typo that affects ban reason limit
